apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: sa-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"] # nouns
  verbs: ["get", "watch", "list"] # actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-reader
  namespace: roboshop
subjects:
- kind: ServiceAccount
  name: roboshopmysqlsecretreader
  namespace: roboshop
roleRef:
 
  kind: Role 
  name:  sa-reader 
  apiGroup: rbac.authorization.k8s.io